name: Save
favicon: null
layout_spectrum: 0.50684
typography_spectrum: 0.5
title: save test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFB'
    - '#28150E'
    - '#A3654A'
    - '#E0BE99'
    - '#FF3039'
  brandStrength: 0.5
  lightness: 0.9964158
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
